---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../base/components/label-transformer

### Si on référence le chart helm ici, on délègue à kustomize l'authent, on ne peut plus exploiter les repositories argocd
### Si on ne référence pas le chart helm ici (multi-sourcing), kustomize n'applique rien

# helmCharts:
#   - name: webapp-color # Nom du chart helm à télécharger dans le dépôt helm
#     repo: oci://demo.goharbor.io/testgohlink # Dépôt helm
#     namespace: default
#     releaseName: webapp-color # Nom de l'applicatif une fois le chart déployé
#     version: 0.1.2 # Version du helm
#     includeCRDs: true
#     valuesFile: ../../base/common-values.yaml
#     additionalValuesFiles:
#       - business-values.yaml
#       - kubernetes-values.yaml