apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hors-prod-without-helmcharts-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators: ## Mise en place de ce système pour pouvoir assigner une version à une app ... Comment faire autrement ?
      - list:
          elements: ## List of helm apps to deploy in the cluster
          - appName: webapp-color
            helmVersion: 0.1.1
      - git:
          repoURL: https://github.com/gohlink/branche-unique.git
          revision: main
          directories:
          - path: apps/{{ .appName }}/env/hors-prod ## could be apps/*/env/hors-prod but how to set helm version then ?
  template:      
    metadata:
      name: '{{ index .path.segments 1 }}'
    spec:
      project: default  ## ?? Maybe appsets files should be defined by project / env instead of just env

      sources:
      - repoURL: https://github.com/gohlink/branche-unique.git
        targetRevision: main
        path: 'apps/{{ .appName }}'
        ref: values

      - repoURL: https://marcusjava.github.io/helm-charts-repo/
        chart: '{{ .appName }}'
        targetRevision: '{{ .helmVersion }}'
        helm:
          releaseName: '{{ .appName }}'
          valueFiles:
          - $values/apps/{{ .appName }}/base/values.yaml
          # - $values/values-overwrite.yaml
          # - $values/values-overwrite-replicas.yaml
          - $values/apps/{{ .appName }}/envs/hors-prod/values-overwrite.yaml
          - $values/apps/{{ .appName }}/envs/hors-prod/values-overwrite-replicas.yaml

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: default ## '{{ index .path.segments 1 }}-{{ index .path.segments 3 }}' ex: webapp-color-hors-prod

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      