---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: default

# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization


# # generators:
# # - helm-chart.yaml

# # apiVersion: kustomize.config.k8s.io/v1beta1
# # kind: Kustomization

# # helmChartInflationGenerator:
# #   - chartRepoUrl: https://marcusjava.github.io/helm-charts-repo/
# #     chartName: webapp-color
# #     releaseName: webapp-color
# #     releaseNamespace: default

# helmCharts:
# - name: webapp-color
#   repo: https://marcusjava.github.io/helm-charts-repo/
#   releaseName: webapp-color
#   namespace: default
#   version: 0.1.1
#   valuesFile: values.yaml


## TODO HERE :
## link to helm resource on arti