apiVersion: builtin
kind: LabelTransformer
metadata:
  name: global-labels
labels:
  name: webapp-color
fieldSpecs:
# - path: metadata/labels
#   create: true
- kind: Deployment
  name: webapp-color-deployment
  path: spec/template/metadata/labels
  create: false