---
components:
  - ../../base/

helmCharts:
  - name: webapp-color
    repo: https://marcusjava.github.io/helm-charts-repo/
    namespace: default
    releaseName: webapp-color-clone
    version: 0.1.1
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-overwrite.yaml
      - values-overwrite-replicas.yaml
